export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkVuem8gTm9kYSIsImVtYWlsIjoiZW56by5ub2RhQGdtYWlsLmNvbSIsImlhdCI6MTcxODcxMzk2MSwiZXhwIjoxNzE5MzE4NzYxLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.RhSB7FTEOSVxH4RVPmjlJjNZRvkQ9FUo9QKxpdcmzKY';
